services:
  postgres:
    image: postgres:latest
    container_name: nazpara_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nazpara
    ports:
      - "5432:5432"