services:
  postgres:
    image: postgres:latest
    container_name: vanpara_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: vanpara
    ports:
      - "5432:5432"