services:
  postgres:
    image: postgres:latest
    container_name: fa
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fa
    ports:
      - "5432:5432"